org.gradle.jvmargs=-Xmx6144m -XX:+UseParallelGC -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.workers.max=6
kotlin.daemon.jvmargs=-Xmx4096m -XX:+UseParallelGC
kotlin.incremental=true
kotlin.incremental.js=true
kotlin.incremental.multiplatform=true
android.useAndroidX=true
android.enableJetifier=false
kotlin.code.style=official

# Enabled parallel sync for Gradle 9.4+
org.gradle.tooling.parallel=true
