pluginManagement {
    repositories {
        maven { url = 'https://repo.huaweicloud.com/repository/maven/gradle-plugin/' }
        maven { url = 'https://repo.huaweicloud.com/repository/maven/google/' }
        maven { url = 'https://repo.huaweicloud.com/repository/maven/' }
        gradlePluginPortal()
        google()
        mavenCentral()
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.PREFER_SETTINGS)
    repositories {
        maven { url = 'https://repo.huaweicloud.com/repository/maven/google/' }
        maven { url = 'https://repo.huaweicloud.com/repository/maven/' }
        maven { url = 'https://jitpack.io' }
        google()
        mavenCentral()
    }
}

rootProject.name = "LumineAndroid"
include ':app'