pluginManagement {
    repositories {
        maven { url = 'https://mirrors.tencent.com/nexus/repository/google/' }
        maven { url = 'https://mirrors.tencent.com/nexus/repository/maven-central/' }
        maven { url = 'https://mirrors.cernet.edu.cn/maven/' }
        maven { url = 'https://repo.huaweicloud.com/repository/maven/' }
        maven { url = 'https://mirrors.tuna.tsinghua.edu.cn/maven/' }

        gradlePluginPortal()
        google()
        mavenCentral()
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.PREFER_SETTINGS)
    repositories {
        maven { url = 'https://mirrors.tencent.com/nexus/repository/google/' }
        maven { url = 'https://mirrors.tencent.com/nexus/repository/maven-central/' }
        maven { url = 'https://mirrors.cernet.edu.cn/maven/' }
        maven { url = 'https://repo.huaweicloud.com/repository/maven/' }
        maven { url = 'https://mirrors.tuna.tsinghua.edu.cn/maven/' }

        google()
        mavenCentral()

        maven { url = 'https://jitpack.io' }
    }
}

rootProject.name = "LumineAndroid"
include ':app'
